<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="1" failed="3" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2020-08-04T20:48:43Z" name="Default suite" finished-at="2020-08-04T20:50:29Z" duration-ms="106027">
    <groups>
    </groups>
    <test started-at="2020-08-04T20:48:43Z" name="Default test" finished-at="2020-08-04T20:50:29Z" duration-ms="106027">
      <class name="CRMloginTest.DataDrivenLogin">
        <test-method is-config="true" signature="launchBrowser()[pri:0, instance:CRMloginTest.DataDrivenLogin@313b2ea6]" started-at="2020-08-04T20:48:43Z" name="launchBrowser" finished-at="2020-08-04T20:48:56Z" duration-ms="12364" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method signature="loginCRM(java.lang.String, java.lang.String)[pri:0, instance:CRMloginTest.DataDrivenLogin@313b2ea6]" started-at="2020-08-04T20:48:56Z" name="loginCRM" data-provider="getData" finished-at="2020-08-04T20:49:06Z" duration-ms="10339" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[selenium@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Selenium]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[login fail expected [https://ui.freecrm.com/home] but found [https://ui.freecrm.com/]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: login fail expected [https://ui.freecrm.com/home] but found [https://ui.freecrm.com/]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at CRMloginTest.DataDrivenLogin.loginCRM(DataDrivenLogin.java:69)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.base/java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginCRM -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:CRMloginTest.DataDrivenLogin@313b2ea6]" started-at="2020-08-04T20:49:06Z" name="closeBrowser" finished-at="2020-08-04T20:49:06Z" duration-ms="107" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
        <test-method is-config="true" signature="launchBrowser()[pri:0, instance:CRMloginTest.DataDrivenLogin@313b2ea6]" started-at="2020-08-04T20:49:06Z" name="launchBrowser" finished-at="2020-08-04T20:49:18Z" duration-ms="12472" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method signature="loginCRM(java.lang.String, java.lang.String)[pri:0, instance:CRMloginTest.DataDrivenLogin@313b2ea6]" started-at="2020-08-04T20:49:18Z" name="loginCRM" data-provider="getData" finished-at="2020-08-04T20:49:29Z" duration-ms="10395" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[seleniumautomation@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Automation]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[login fail expected [https://ui.freecrm.com/home] but found [https://ui.freecrm.com/]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: login fail expected [https://ui.freecrm.com/home] but found [https://ui.freecrm.com/]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at CRMloginTest.DataDrivenLogin.loginCRM(DataDrivenLogin.java:69)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.base/java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginCRM -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:CRMloginTest.DataDrivenLogin@313b2ea6]" started-at="2020-08-04T20:49:29Z" name="closeBrowser" finished-at="2020-08-04T20:49:33Z" duration-ms="4340" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
        <test-method is-config="true" signature="launchBrowser()[pri:0, instance:CRMloginTest.DataDrivenLogin@313b2ea6]" started-at="2020-08-04T20:49:33Z" name="launchBrowser" finished-at="2020-08-04T20:49:45Z" duration-ms="12130" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method signature="loginCRM(java.lang.String, java.lang.String)[pri:0, instance:CRMloginTest.DataDrivenLogin@313b2ea6]" started-at="2020-08-04T20:49:45Z" name="loginCRM" data-provider="getData" finished-at="2020-08-04T20:50:01Z" duration-ms="15405" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[seleniumscripts@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[SeleniumScripts]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[login fail expected [https://ui.freecrm.com/home] but found [https://ui.freecrm.com/]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: login fail expected [https://ui.freecrm.com/home] but found [https://ui.freecrm.com/]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at CRMloginTest.DataDrivenLogin.loginCRM(DataDrivenLogin.java:69)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.base/java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginCRM -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:CRMloginTest.DataDrivenLogin@313b2ea6]" started-at="2020-08-04T20:50:01Z" name="closeBrowser" finished-at="2020-08-04T20:50:01Z" duration-ms="48" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
        <test-method is-config="true" signature="launchBrowser()[pri:0, instance:CRMloginTest.DataDrivenLogin@313b2ea6]" started-at="2020-08-04T20:50:01Z" name="launchBrowser" finished-at="2020-08-04T20:50:12Z" duration-ms="11540" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method signature="loginCRM(java.lang.String, java.lang.String)[pri:0, instance:CRMloginTest.DataDrivenLogin@313b2ea6]" started-at="2020-08-04T20:50:12Z" name="loginCRM" data-provider="getData" finished-at="2020-08-04T20:50:29Z" duration-ms="16378" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[seleniumscripts.automation@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Automation123]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginCRM -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:CRMloginTest.DataDrivenLogin@313b2ea6]" started-at="2020-08-04T20:50:29Z" name="closeBrowser" finished-at="2020-08-04T20:50:29Z" duration-ms="49" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- CRMloginTest.DataDrivenLogin -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
